general = {
    name = "Routel Desktop";
    interpolation = "soxr";
    dbus_service_bus = "session";
    mpris_service_bus = "session";
};

metadata = {
    enabled = true;
    include_cover_art = true;
};

